blank_issues_enabled: false
contact_links:
  - name: ☀️ Core Issue
    url: https://github.com/co-cart/cocart-core
    about: If you have issues related to the core of CoCart or the Cart API, please report them to this repository.

  - name: 🖥️ Admin Issue
    url: https://github.com/co-cart/cocart-admin
    about: If you have issues related to CoCart in the WordPress Dashboard, please report them to this repository.

  - name: 🍦 Products API Issue
    url: https://github.com/co-cart/cocart-products-api
    about: If you have issues related to the Products API specifically, please report them to this repository.

  - name: 🔌 Compatibility Issue
    url: https://github.com/co-cart/cocart-compatibility
    about: If you have a compatibility issue specifically with a certain plugin and WooCommerce extension, please report them to this repository.

  - name: 📂 Third Party Issue
    url: https://github.com/co-cart/cocart-third-party
    about: If you have a compatibility issue specifically with support for specific plugins, WooCommerce extensions and web hosts, please report them to this repository.

  - name: 🔥 Pro Issue
    url: https://github.com/co-cart/cocart-pro-reports
    about: If you have issues related to CoCart Pro, please report them to this repository.

  - name: ❓ Support Question
    url: https://wordpress.org/support/plugin/cart-rest-api-for-woocommerce/
    about: If you have a question please use the support forum!

  - name: 😄 Discord
    url: https://cocart.xyz/community
    about: Join the official community for CoCart on Discord.
